#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# DYNAMIC WAVE CONFIGURATION GENERATOR
# ═══════════════════════════════════════════════════════════════════════════════
# Generates docker-compose services for any wave number
# Ensures wave-specific configuration is always correct
# Usage: ./generate-wave-config.sh <wave_number> [project_root]
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ─────────────────────────────────────────────────────────────────────────────
# ARGUMENTS
# ─────────────────────────────────────────────────────────────────────────────

if [ -z "${1:-}" ]; then
    echo -e "${RED}Error: Wave number required${NC}"
    echo "Usage: $0 <wave_number> [project_root]"
    echo "Example: $0 4 /path/to/project"
    exit 1
fi

WAVE=$1
PROJECT_ROOT="${2:-.}"
cd "$PROJECT_ROOT"

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN} WAVE $WAVE CONFIGURATION GENERATOR${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Load environment
if [ -f ".env" ]; then
    source .env
fi

# ─────────────────────────────────────────────────────────────────────────────
# COUNT STORIES
# ─────────────────────────────────────────────────────────────────────────────

STORIES_DIR="stories/wave${WAVE}"
FE_STORIES=""
BE_STORIES=""

if [ -d "$STORIES_DIR" ]; then
    # Find frontend stories
    for story in $(find "$STORIES_DIR" -name "*.json" 2>/dev/null); do
        AGENT=$(jq -r '.agent // "unknown"' "$story" 2>/dev/null)
        STORY_FILE=$(basename "$story")
        if [ "$AGENT" = "frontend" ]; then
            FE_STORIES="$FE_STORIES $STORY_FILE"
        elif [ "$AGENT" = "backend" ]; then
            BE_STORIES="$BE_STORIES $STORY_FILE"
        fi
    done
fi

FE_COUNT=$(echo "$FE_STORIES" | wc -w | tr -d ' ')
BE_COUNT=$(echo "$BE_STORIES" | wc -w | tr -d ' ')

echo -e "${BLUE}Stories found:${NC}"
echo "  Frontend: $FE_COUNT"
echo "  Backend:  $BE_COUNT"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# GENERATE DOCKER COMPOSE FRAGMENT
# ─────────────────────────────────────────────────────────────────────────────

COMPOSE_FRAGMENT="docker-compose.wave${WAVE}.yml"

echo -e "${YELLOW}Generating docker-compose fragment: $COMPOSE_FRAGMENT${NC}"

cat > "$COMPOSE_FRAGMENT" <<EOF
# ═══════════════════════════════════════════════════════════════════════════════
# WAVE $WAVE DOCKER COMPOSE SERVICES
# ═══════════════════════════════════════════════════════════════════════════════
# Auto-generated by generate-wave-config.sh
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# ═══════════════════════════════════════════════════════════════════════════════

services:
  # ─────────────────────────────────────────────────────────────────────────────
  # WAVE $WAVE - FRONTEND DEVELOPER
  # ─────────────────────────────────────────────────────────────────────────────
  wave${WAVE}-fe-dev:
    image: maf-claude-agent:latest
    container_name: wave${WAVE}-fe-dev
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
      - AGENT_ROLE=frontend-dev
      - WAVE=$WAVE
      - STORY_BUDGET=\${STORY_BUDGET:-0.50}
      - SLACK_WEBHOOK_URL=\${SLACK_WEBHOOK_URL:-}
    volumes:
      - ./worktrees/fe-dev:/app
      - ./stories/wave${WAVE}:/stories:ro
      - ./.claude:/signals
      - ./CLAUDE.md:/app/CLAUDE.md:ro
    working_dir: /app
    command: >
      claude -p "You are FE-Dev agent for Wave $WAVE.

      CRITICAL: Read /app/CLAUDE.md first for all protocols.

      Stories to implement: /stories/
      Signal directory: /signals/

      For each frontend story:
      1. Read the story JSON
      2. Implement the component/feature
      3. Write tests
      4. Send Slack notification via webhook
      5. Create completion signal

      When ALL frontend stories complete:
      Create signal: /signals/signal-wave${WAVE}-gate3-fe-complete.json

      Budget: \$\${STORY_BUDGET:-0.50} per story"
    networks:
      - maf-network
    restart: "no"

  # ─────────────────────────────────────────────────────────────────────────────
  # WAVE $WAVE - BACKEND DEVELOPER
  # ─────────────────────────────────────────────────────────────────────────────
  wave${WAVE}-be-dev:
    image: maf-claude-agent:latest
    container_name: wave${WAVE}-be-dev
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
      - AGENT_ROLE=backend-dev
      - WAVE=$WAVE
      - STORY_BUDGET=\${STORY_BUDGET:-0.50}
      - SLACK_WEBHOOK_URL=\${SLACK_WEBHOOK_URL:-}
    volumes:
      - ./worktrees/be-dev:/app
      - ./stories/wave${WAVE}:/stories:ro
      - ./.claude:/signals
      - ./CLAUDE.md:/app/CLAUDE.md:ro
    working_dir: /app
    command: >
      claude -p "You are BE-Dev agent for Wave $WAVE.

      CRITICAL: Read /app/CLAUDE.md first for all protocols.

      Stories to implement: /stories/
      Signal directory: /signals/

      For each backend story:
      1. Read the story JSON
      2. Implement the API/migration/service
      3. Write tests
      4. Send Slack notification via webhook
      5. Create completion signal

      When ALL backend stories complete:
      Create signal: /signals/signal-wave${WAVE}-gate3-be-complete.json

      Budget: \$\${STORY_BUDGET:-0.50} per story"
    networks:
      - maf-network
    restart: "no"

  # ─────────────────────────────────────────────────────────────────────────────
  # WAVE $WAVE - QA AGENT
  # ─────────────────────────────────────────────────────────────────────────────
  wave${WAVE}-qa:
    image: maf-claude-agent:latest
    container_name: wave${WAVE}-qa
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
      - AGENT_ROLE=qa
      - WAVE=$WAVE
      - STORY_BUDGET=\${STORY_BUDGET:-0.50}
      - SLACK_WEBHOOK_URL=\${SLACK_WEBHOOK_URL:-}
    volumes:
      - ./worktrees/qa:/app
      - ./stories/wave${WAVE}:/stories:ro
      - ./.claude:/signals
      - ./CLAUDE.md:/app/CLAUDE.md:ro
    working_dir: /app
    command: >
      claude -p "You are QA agent for Wave $WAVE.

      CRITICAL: Read /app/CLAUDE.md first for all protocols.

      WAIT for BOTH signals before starting:
      - /signals/signal-wave${WAVE}-gate3-fe-complete.json
      - /signals/signal-wave${WAVE}-gate3-be-complete.json

      Then validate:
      1. All story acceptance criteria met
      2. Tests pass (npm test)
      3. Build succeeds (npm run build)
      4. No TypeScript errors
      5. Code quality checks

      On SUCCESS: Create /signals/signal-wave${WAVE}-gate4-approved.json
      On FAILURE: Create /signals/signal-wave${WAVE}-gate4-rejected.json with issues

      Send Slack notification with results."
    networks:
      - maf-network
    restart: "no"

networks:
  maf-network:
    driver: bridge
EOF

echo -e "${GREEN}✓ Generated: $COMPOSE_FRAGMENT${NC}"

# ─────────────────────────────────────────────────────────────────────────────
# CHECK IF MAIN COMPOSE FILE NEEDS UPDATE
# ─────────────────────────────────────────────────────────────────────────────

MAIN_COMPOSE="docker-compose-v11.2.yml"

if [ -f "$MAIN_COMPOSE" ]; then
    if ! grep -q "wave${WAVE}-fe-dev:" "$MAIN_COMPOSE" 2>/dev/null; then
        echo ""
        echo -e "${YELLOW}Wave $WAVE services NOT found in $MAIN_COMPOSE${NC}"
        echo -e "${YELLOW}To use standalone: docker compose -f $COMPOSE_FRAGMENT up${NC}"
        echo -e "${YELLOW}To merge into main compose file, append the services section${NC}"
        echo ""

        # Offer to append to main compose
        echo -e "${CYAN}Would you like to append Wave $WAVE services to $MAIN_COMPOSE? (y/n)${NC}"
        read -p "> " APPEND_CHOICE

        if [ "$APPEND_CHOICE" = "y" ] || [ "$APPEND_CHOICE" = "Y" ]; then
            echo "" >> "$MAIN_COMPOSE"
            echo "# ═══════════════════════════════════════════════════════════════════════════════" >> "$MAIN_COMPOSE"
            echo "# WAVE $WAVE SERVICES (auto-generated $(date '+%Y-%m-%d'))" >> "$MAIN_COMPOSE"
            echo "# ═══════════════════════════════════════════════════════════════════════════════" >> "$MAIN_COMPOSE"

            # Extract services section (skip the header and networks)
            sed -n '/^services:/,/^networks:/p' "$COMPOSE_FRAGMENT" | head -n -2 | tail -n +2 >> "$MAIN_COMPOSE"

            echo -e "${GREEN}✓ Wave $WAVE services appended to $MAIN_COMPOSE${NC}"
        fi
    else
        echo -e "${GREEN}✓ Wave $WAVE services already exist in $MAIN_COMPOSE${NC}"
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# CREATE WAVE-SPECIFIC .ENV TEMPLATE
# ─────────────────────────────────────────────────────────────────────────────

ENV_TEMPLATE=".env.wave${WAVE}.template"

cat > "$ENV_TEMPLATE" <<EOF
# ═══════════════════════════════════════════════════════════════════════════════
# WAVE $WAVE ENVIRONMENT CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════
# Auto-generated by generate-wave-config.sh
# Copy to .env and fill in values
# ═══════════════════════════════════════════════════════════════════════════════

# Wave Configuration
WAVE=$WAVE
WAVE_BUDGET=${WAVE_BUDGET:-2.00}
STORY_BUDGET=${STORY_BUDGET:-0.50}

# Stories for this wave
WAVE${WAVE}_FE_STORIES="$FE_STORIES"
WAVE${WAVE}_BE_STORIES="$BE_STORIES"
WAVE${WAVE}_TOTAL_STORIES=$((FE_COUNT + BE_COUNT))

# Poll intervals (seconds)
POLL_INTERVAL=${POLL_INTERVAL:-10}
MAX_RETRIES=${MAX_RETRIES:-3}

# Required environment variables (must be set in main .env):
# ANTHROPIC_API_KEY=sk-ant-...
# SLACK_WEBHOOK_URL=https://hooks.slack.com/...
# NEXT_PUBLIC_SUPABASE_URL=https://xxx.supabase.co
# NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ...
# GITHUB_TOKEN=ghp_...
# GITHUB_REPO=owner/repo
EOF

echo -e "${GREEN}✓ Generated: $ENV_TEMPLATE${NC}"

# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN} WAVE $WAVE CONFIGURATION COMPLETE${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Generated files:"
echo -e "  ${GREEN}✓${NC} $COMPOSE_FRAGMENT"
echo -e "  ${GREEN}✓${NC} $ENV_TEMPLATE"
echo ""
echo "To launch Wave $WAVE:"
echo ""
echo "  Option 1 (standalone):"
echo -e "  ${BLUE}docker compose -f $COMPOSE_FRAGMENT up${NC}"
echo ""
echo "  Option 2 (if services added to main compose):"
echo -e "  ${BLUE}docker compose -f $MAIN_COMPOSE up wave${WAVE}-fe-dev wave${WAVE}-be-dev wave${WAVE}-qa${NC}"
echo ""
echo "Before launching, run:"
echo -e "  ${BLUE}./scripts/validate-infrastructure.sh${NC}"
echo -e "  ${BLUE}./scripts/wave-preflight.sh $WAVE${NC}"
echo -e "  ${BLUE}./scripts/maf-launch.sh $WAVE${NC}"
echo ""
